import * as THREE from 'https://unpkg.com/three@0.164.1/build/three.module.js';

const canvas=document.getElementById('game');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));
renderer.shadowMap.enabled=true;
const scene=new THREE.Scene();
scene.background=new THREE.Color(0x11151d);
scene.fog=new THREE.Fog(0x11151d,38,96);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,0.1,160);
const clock=new THREE.Clock();
const world={radius:24,wave:1,phase:'menu',kills:0,shake:0,combo:0,comboTimer:0,bossWaveEvery:5,score:0};
const input={keys:new Set(),mouse:new THREE.Vector2(innerWidth/2,innerHeight/2),punch:false};
const enemies=[];const particles=[];
const player={mesh:null,hp:100,maxHp:100,speed:10,damage:22,cooldown:0,dash:0,dashCooldown:0,invuln:0,crit:.08,regen:0,armor:0,punchRange:2.15,knockback:6,pos:new THREE.Vector3(),dir:0};
const mats={sand:new THREE.MeshStandardMaterial({color:0xb68a4b,roughness:.95}),stone:new THREE.MeshStandardMaterial({color:0x79746d}),darkStone:new THREE.MeshStandardMaterial({color:0x3c3b3d}),player:new THREE.MeshStandardMaterial({color:0x3b77d6}),skin:new THREE.MeshStandardMaterial({color:0xdca56b}),goblin:new THREE.MeshStandardMaterial({color:0x62a34b}),goblinFast:new THREE.MeshStandardMaterial({color:0x78c85c}),goblinTank:new THREE.MeshStandardMaterial({color:0x4f7d3f}),boss:new THREE.MeshStandardMaterial({color:0x7b3ba8,emissive:0x170024}),red:new THREE.MeshStandardMaterial({color:0xd84a3a}),gold:new THREE.MeshStandardMaterial({color:0xd6a23b,emissive:0x1e1400})};
function addLights(){scene.add(new THREE.HemisphereLight(0xf3d8a0,0x242833,1.8));const sun=new THREE.DirectionalLight(0xffe2a3,2.4);sun.position.set(20,28,10);sun.castShadow=true;scene.add(sun);} 
function makeColosseum(){const floor=new THREE.Mesh(new THREE.CylinderGeometry(world.radius,world.radius,1,128),mats.sand);floor.receiveShadow=true;floor.position.y=-.55;scene.add(floor);const wall=new THREE.Mesh(new THREE.CylinderGeometry(world.radius+2.2,world.radius+2.2,5,128,1,true),mats.stone);wall.position.y=1.8;scene.add(wall);for(let i=0;i<36;i++){const a=i/36*Math.PI*2;const block=new THREE.Mesh(new THREE.BoxGeometry(1.25,4.9,1.25),mats.darkStone);block.position.set(Math.cos(a)*(world.radius+1.8),1.75,Math.sin(a)*(world.radius+1.8));scene.add(block);}}
function makeCharacter(mat,scale=1){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.45*scale,.9*scale,6,10),mat);body.position.y=.9*scale;const head=new THREE.Mesh(new THREE.SphereGeometry(.36*scale,16,12),mat===mats.player?mats.skin:mat);head.position.y=1.72*scale;const leftFist=new THREE.Mesh(new THREE.SphereGeometry(.16*scale,10,8),mats.skin);leftFist.position.set(-.52*scale,.95*scale,-.2*scale);const rightFist=leftFist.clone();rightFist.position.x=.52*scale;g.add(body,head,leftFist,rightFist);g.userData={leftFist,rightFist,bob:Math.random()*10};return g;}
function spawnEnemy(type='normal'){const a=Math.random()*Math.PI*2;const r=world.radius-2;const boss=type==='boss';const fast=type==='fast';const tank=type==='tank';const mat=boss?mats.boss:fast?mats.goblinFast:tank?mats.goblinTank:mats.goblin;const scale=boss?1.45:tank?.95:.72+Math.random()*.16;const e={type,mesh:makeCharacter(mat,scale),hp:boss?260+world.wave*32:tank?62+world.wave*12:26+world.wave*7,speed:boss?2.2:fast?5+tank:2.5,attack:boss?19:fast?8:12,cooldown:Math.random(),knock:new THREE.Vector3()};e.mesh.position.set(Math.cos(a)*r,0,Math.sin(a)*r);scene.add(e.mesh);enemies.push(e);} 
function clearEnemies(){while(enemies.length)scene.remove(enemies.pop().mesh);} 
function spawnWave(){clearEnemies();if(world.wave%world.bossWaveEvery===0){spawnEnemy('boss');for(let i=0;i<5;i++)spawnEnemy(i%2?'fast':'normal');}else{const count=5+world.wave*2;for(let i=0;i<count;i++){const roll=Math.random();spawnEnemy(roll<.18?'fast':roll<.32?'tank':'normal');}}document.getElementById('stateText').textContent=world.wave%world.bossWaveEvery===0?`Boss Wave ${world.wave}`:`Wave ${world.wave}`;}
function startRun(){world.wave=1;world.kills=0;world.phase='combat';world.combo=0;world.score=0;player.hp=player.maxHp=100;player.speed=10;player.damage=22;player.crit=.08;player.regen=0;player.armor=0;player.mesh.position.set(0,0,0);spawnWave();hidePanel();}
const rewards=[['rest','Recover HP'],['damage','More damage'],['speed','More speed'],['armor','More armor'],['crit','More crit']];
function chooseReward(kind){if(kind==='rest')player.hp=Math.min(player.maxHp,player.hp+45);if(kind==='damage')player.damage+=8;if(kind==='speed')player.speed+=1.4;if(kind==='armor')player.armor+=2;if(kind==='crit')player.crit+=.07;world.wave++;world.phase='combat';spawnWave();hidePanel();}
function showReward(){world.phase='reward';const p=document.getElementById('centerPanel');p.className='panel';p.innerHTML=`<h2>Wave cleared</h2><div class='choices'>${rewards.map(r=>`<button data-choice='${r[0]}'>${r[0]}<span class='small'>${r[1]}</span></button>`).join('')}</div>`;p.querySelectorAll('button').forEach(b=>b.onclick=()=>chooseReward(b.dataset.choice));}
function showMenu(){const p=document.getElementById('centerPanel');p.className='panel';p.innerHTML=`<h1>Goblin Colosseum</h1><p>Fight goblin kindergarten kids in a roguelike colosseum.</p><button id='start'>Start Run</button>`;p.querySelector('#start').onclick=startRun;}
function hidePanel(){document.getElementById('centerPanel').className='panel hidden';}
function gameOver(){world.phase='dead';clearEnemies();const p=document.getElementById('centerPanel');p.className='panel';p.innerHTML=`<h2>Run ended</h2><p>Wave ${world.wave}</p><button id='restart'>Restart</button>`;p.querySelector('#restart').onclick=startRun;}
function updatePlayer(dt){player.cooldown-=dt;player.invuln-=dt;player.dash-=dt;const v=new THREE.Vector3((input.keys.has('KeyD')?1:0)-(input.keys.has('KeyA')?1:0),0,(input.keys.has('KeyS')?1:0)-(input.keys.has('KeyW')?1:0));if(v.lengthSq())v.normalize();const spd=player.speed*(player.dash>0?2.2:1);player.mesh.position.addScaledVector(v,spd*dt);const len=player.mesh.position.length();if(len>world.radius-1.3)player.mesh.position.multiplyScalar((world.radius-1.3)/len);player.pos.copy(player.mesh.position);const aim=screenToArena(input.mouse.x,input.mouse.y);player.dir=Math.atan2(aim.x-player.pos.x,aim.z-player.pos.z);player.mesh.rotation.y=player.dir;if(input.punch&&player.cooldown<=0)punch();}
function punch(){player.cooldown=.34;world.shake=.08;const forward=new THREE.Vector3(Math.sin(player.dir),0,Math.cos(player.dir));for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];const to=e.mesh.position.clone().sub(player.pos);const dist=to.length();if(dist<player.punchRange&&to.normalize().dot(forward)>.35){const crit=Math.random()<player.crit;e.hp-=player.damage*(crit?2:1);e.knock.addScaledVector(forward,crit?player.knockback*1.7:player.knockback);burst(e.mesh.position,crit?12:6,crit?mats.gold.color:mats.red.color);if(e.hp<=0){scene.remove(e.mesh);enemies.splice(i,1);world.kills++;world.combo++;world.score+=100;}}}if(enemies.length===0&&world.phase==='combat')showReward();}
function updateEnemies(dt){for(const e of enemies){const to=player.pos.clone().sub(e.mesh.position);const d=to.length();if(d>.01)to.normalize();e.mesh.position.addScaledVector(to,e.speed*dt);e.mesh.position.addScaledVector(e.knock,dt);e.knock.multiplyScalar(Math.pow(.02,dt));e.mesh.rotation.y=Math.atan2(to.x,to.z);e.cooldown-=dt;if(d<1.25&&e.cooldown<=0&&player.invuln<=0){player.hp-=Math.max(1,e.attack-player.armor);player.invuln=.3;e.cooldown=1.1;world.shake=.14;burst(player.pos,7,mats.red.color);if(player.hp<=0)gameOver();}}}
function burst(pos,count,color){for(let i=0;i<count;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.07,8,6),new THREE.MeshBasicMaterial({color}));m.position.copy(pos).add(new THREE.Vector3(0,1,0));scene.add(m);particles.push({mesh:m,life:.45,vel:new THREE.Vector3((Math.random()-.5)*5,Math.random()*4,(Math.random()-.5)*5)});}}
function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.vel.y-=9*dt;p.mesh.position.addScaledVector(p.vel,dt);if(p.life<=0){scene.remove(p.mesh);particles.splice(i,1);}}}
function screenToArena(x,y){const rect=canvas.getBoundingClientRect();const ndc=new THREE.Vector2((x/rect.width)*2-1,-(y/rect.height)*2+1);const ray=new THREE.Raycaster();ray.setFromCamera(ndc,camera);const t=-ray.ray.origin.y/ray.ray.direction.y;return ray.ray.origin.clone().addScaledVector(ray.ray.direction,t);} 
function updateCamera(){const offset=new THREE.Vector3(0,21,23);camera.position.copy(player.pos).add(offset);if(world.shake>0)camera.position.add(new THREE.Vector3((Math.random()-.5)*world.shake*3,0,(Math.random()-.5)*world.shake*3));camera.lookAt(player.pos.x,0,player.pos.z);world.shake=Math.max(0,world.shake-.02);} 
function updateStats(){document.getElementById('stats').innerHTML=`HP ${Math.ceil(player.hp)} / ${player.maxHp}<br>Damage ${player.damage}<br>Armor ${player.armor}<br>Combo ${world.combo}<br>Score ${world.score}<br>Goblins ${enemies.length}`;} 
function loop(){const dt=Math.min(clock.getDelta(),.033);if(world.phase==='combat'){updatePlayer(dt);updateEnemies(dt);}updateParticles(dt);updateCamera();updateStats();renderer.render(scene,camera);requestAnimationFrame(loop);} 
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}
addEventListener('resize',resize);addEventListener('keydown',e=>{input.keys.add(e.code);if(e.code==='Space')player.dash=.18;if(e.code==='KeyF')startRun();});addEventListener('keyup',e=>input.keys.delete(e.code));addEventListener('mousemove',e=>input.mouse.set(e.clientX,e.clientY));addEventListener('mousedown',e=>{if(e.button===0)input.punch=true;});addEventListener('mouseup',e=>{if(e.button===0)input.punch=false;});
addLights();makeColosseum();player.mesh=makeCharacter(mats.player,1);scene.add(player.mesh);resize();showMenu();loop();