import * as THREE from 'https://unpkg.com/three@0.164.1/build/three.module.js';

const canvas=document.getElementById('game');
const renderer=new THREE.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'});
renderer.setPixelRatio(1);
renderer.shadowMap.enabled=true;
renderer.shadowMap.type=THREE.BasicShadowMap;
const scene=new THREE.Scene();
scene.background=new THREE.Color(0x08070a);
scene.fog=new THREE.FogExp2(0x08070a,0.032);
const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,0.1,120);
const clock=new THREE.Clock();
const world={radius:24,wave:1,phase:'menu',kills:0,shake:0,combo:0,comboTimer:0,bossWaveEvery:5,score:0};
const input={keys:new Set(),mouse:new THREE.Vector2(innerWidth/2,innerHeight/2),punch:false};
const enemies=[];const particles=[];
const player={mesh:null,hp:100,maxHp:100,speed:10,damage:22,cooldown:0,dash:0,dashCooldown:0,invuln:0,crit:.08,regen:0,armor:0,punchRange:3.35,knockback:7.5,pos:new THREE.Vector3(),dir:0};
function mat(color,emissive=0x000000){return new THREE.MeshLambertMaterial({color,emissive});}
const mats={sand:mat(0x4a3525),stone:mat(0x2a2526),darkStone:mat(0x171519),player:mat(0x26395f),skin:mat(0x9c6744),goblin:mat(0x315b37),goblinFast:mat(0x456f37),goblinTank:mat(0x263f32),boss:mat(0x42245d,0x100018),red:mat(0x8b2420),gold:mat(0xa06f25,0x181000),black:mat(0x050406),bone:mat(0xb8a77f)};
function addLights(){scene.add(new THREE.HemisphereLight(0x3a2e24,0x09070a,1.15));const moon=new THREE.DirectionalLight(0x8b8fb5,1.8);moon.position.set(-16,26,9);moon.castShadow=true;moon.shadow.mapSize.set(512,512);scene.add(moon);const fire=new THREE.PointLight(0x9b351e,2.8,36);fire.position.set(0,5,-17);scene.add(fire);} 
function makeColosseum(){const floor=new THREE.Mesh(new THREE.CylinderGeometry(world.radius,world.radius,1,32),mats.sand);floor.receiveShadow=true;floor.position.y=-.55;scene.add(floor);const wall=new THREE.Mesh(new THREE.CylinderGeometry(world.radius+2.2,world.radius+2.2,5,40,1,true),mats.stone);wall.position.y=1.8;scene.add(wall);const upper=new THREE.Mesh(new THREE.CylinderGeometry(world.radius+2.6,world.radius+2.6,.7,40,1,true),mats.darkStone);upper.position.y=4.45;scene.add(upper);for(let i=0;i<28;i++){const a=i/28*Math.PI*2;const block=new THREE.Mesh(new THREE.BoxGeometry(1.1,4.9,1.1),mats.darkStone);block.position.set(Math.cos(a)*(world.radius+1.8),1.75,Math.sin(a)*(world.radius+1.8));block.rotation.y=-a;scene.add(block);if(i%4===0){const spike=new THREE.Mesh(new THREE.ConeGeometry(.45,1.8,4),mats.black);spike.position.set(Math.cos(a)*(world.radius+1.1),5.2,Math.sin(a)*(world.radius+1.1));spike.rotation.y=a;scene.add(spike);}}for(let i=0;i<10;i++){const a=i/10*Math.PI*2;const bone=new THREE.Mesh(new THREE.BoxGeometry(.18,.18,2.8),mats.bone);bone.position.set(Math.cos(a)*14,.08,Math.sin(a)*14);bone.rotation.y=a+Math.PI/2;scene.add(bone);}}
function makeCharacter(matBody,scale=1){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.45*scale,.9*scale,3,5),matBody);body.position.y=.9*scale;body.castShadow=true;const headMat=matBody===mats.player?mats.skin:matBody;const head=new THREE.Mesh(new THREE.SphereGeometry(.36*scale,7,5),headMat);head.position.y=1.72*scale;head.castShadow=true;const leftFist=new THREE.Mesh(new THREE.SphereGeometry(.18*scale,6,4),headMat);leftFist.position.set(-.58*scale,.92*scale,-.35*scale);const rightFist=leftFist.clone();rightFist.position.x=.58*scale;const nose=new THREE.Mesh(new THREE.ConeGeometry(.12*scale,.35*scale,4),matBody===mats.player?mats.skin:mats.black);nose.position.set(0,1.7*scale,.34*scale);nose.rotation.x=Math.PI/2;const leftEar=new THREE.Mesh(new THREE.ConeGeometry(.16*scale,.38*scale,4),headMat);leftEar.position.set(-.37*scale,1.73*scale,0);leftEar.rotation.z=Math.PI/2;const rightEar=leftEar.clone();rightEar.position.x=.37*scale;rightEar.rotation.z=-Math.PI/2;g.add(body,head,leftFist,rightFist,nose,leftEar,rightEar);g.userData={leftFist,rightFist,bob:Math.random()*10};return g;}
function spawnEnemy(type='normal'){const a=Math.random()*Math.PI*2;const r=world.radius-2;const boss=type==='boss';const fast=type==='fast';const tank=type==='tank';const matBody=boss?mats.boss:fast?mats.goblinFast:tank?mats.goblinTank:mats.goblin;const scale=boss?1.45:tank?.95:.72+Math.random()*.16;const e={type,mesh:makeCharacter(matBody,scale),hp:boss?260+world.wave*32:tank?62+world.wave*12:26+world.wave*7,speed:boss?2.2:fast?5.1:tank?1.9:2.7,attack:boss?19:fast?8:12,cooldown:Math.random(),knock:new THREE.Vector3()};e.mesh.position.set(Math.cos(a)*r,0,Math.sin(a)*r);scene.add(e.mesh);enemies.push(e);} 
function clearEnemies(){while(enemies.length)scene.remove(enemies.pop().mesh);} 
function spawnWave(){clearEnemies();if(world.wave%world.bossWaveEvery===0){spawnEnemy('boss');for(let i=0;i<5;i++)spawnEnemy(i%2?'fast':'normal');}else{const count=5+world.wave*2;for(let i=0;i<count;i++){const roll=Math.random();spawnEnemy(roll<.18?'fast':roll<.32?'tank':'normal');}}document.getElementById('stateText').textContent=world.wave%world.bossWaveEvery===0?`Boss Wave ${world.wave}`:`Wave ${world.wave}`;}
function startRun(){world.wave=1;world.kills=0;world.phase='combat';world.combo=0;world.score=0;player.hp=player.maxHp=100;player.speed=10;player.damage=22;player.crit=.08;player.regen=0;player.armor=0;player.punchRange=3.35;player.knockback=7.5;player.mesh.position.set(0,0,0);spawnWave();hidePanel();}
const rewards=[['rest','Recover HP'],['damage','More damage'],['speed','More speed'],['armor','More armor'],['crit','More crit'],['range','Longer curse-reach fists']];
function chooseReward(kind){if(kind==='rest')player.hp=Math.min(player.maxHp,player.hp+45);if(kind==='damage')player.damage+=8;if(kind==='speed')player.speed+=1.4;if(kind==='armor')player.armor+=2;if(kind==='crit')player.crit+=.07;if(kind==='range')player.punchRange+=.45;world.wave++;world.phase='combat';spawnWave();hidePanel();}
function showReward(){world.phase='reward';const p=document.getElementById('centerPanel');p.className='panel';p.innerHTML=`<h2>Wave cleared</h2><p>The pit offers a vile blessing.</p><div class='choices'>${rewards.map(r=>`<button data-choice='${r[0]}'>${r[0]}<span class='small'>${r[1]}</span></button>`).join('')}</div>`;p.querySelectorAll('button').forEach(b=>b.onclick=()=>chooseReward(b.dataset.choice));}
function showMenu(){const p=document.getElementById('centerPanel');p.className='panel';p.innerHTML=`<h1>Goblin Colosseum</h1><p>A dark fantasy PS2-style bare-knuckle roguelike. Fight warped goblin children in a cursed arena.</p><button id='start'>Start Run</button>`;p.querySelector('#start').onclick=startRun;}
function hidePanel(){document.getElementById('centerPanel').className='panel hidden';}
function gameOver(){world.phase='dead';clearEnemies();const p=document.getElementById('centerPanel');p.className='panel';p.innerHTML=`<h2>Run ended</h2><p>The colosseum keeps your bones. Wave ${world.wave}</p><button id='restart'>Restart</button>`;p.querySelector('#restart').onclick=startRun;}
function updatePlayer(dt){player.cooldown-=dt;player.invuln-=dt;player.dash-=dt;const v=new THREE.Vector3((input.keys.has('KeyD')?1:0)-(input.keys.has('KeyA')?1:0),0,(input.keys.has('KeyS')?1:0)-(input.keys.has('KeyW')?1:0));if(v.lengthSq())v.normalize();const spd=player.speed*(player.dash>0?2.2:1);player.mesh.position.addScaledVector(v,spd*dt);const len=player.mesh.position.length();if(len>world.radius-1.3)player.mesh.position.multiplyScalar((world.radius-1.3)/len);player.pos.copy(player.mesh.position);const aim=screenToArena(input.mouse.x,input.mouse.y);player.dir=Math.atan2(aim.x-player.pos.x,aim.z-player.pos.z);player.mesh.rotation.y=player.dir;if(input.punch&&player.cooldown<=0)punch();}
function punch(){player.cooldown=.34;world.shake=.08;const forward=new THREE.Vector3(Math.sin(player.dir),0,Math.cos(player.dir));const arc=.18+Math.min(player.punchRange,5)*.02;for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];const to=e.mesh.position.clone().sub(player.pos);const dist=to.length();if(dist<player.punchRange&&to.normalize().dot(forward)>arc){const crit=Math.random()<player.crit;e.hp-=player.damage*(crit?2:1);e.knock.addScaledVector(forward,crit?player.knockback*1.7:player.knockback);burst(e.mesh.position,crit?12:6,crit?mats.gold.color:mats.red.color);if(e.hp<=0){scene.remove(e.mesh);enemies.splice(i,1);world.kills++;world.combo++;world.score+=100;}}}if(enemies.length===0&&world.phase==='combat')showReward();}
function updateEnemies(dt){for(const e of enemies){const to=player.pos.clone().sub(e.mesh.position);const d=to.length();if(d>.01)to.normalize();e.mesh.position.addScaledVector(to,e.speed*dt);e.mesh.position.addScaledVector(e.knock,dt);e.knock.multiplyScalar(Math.pow(.02,dt));e.mesh.rotation.y=Math.atan2(to.x,to.z);e.cooldown-=dt;if(d<1.25&&e.cooldown<=0&&player.invuln<=0){player.hp-=Math.max(1,e.attack-player.armor);player.invuln=.3;e.cooldown=1.1;world.shake=.14;burst(player.pos,7,mats.red.color);if(player.hp<=0)gameOver();}}}
function burst(pos,count,color){for(let i=0;i<count;i++){const m=new THREE.Mesh(new THREE.TetrahedronGeometry(.095,0),new THREE.MeshBasicMaterial({color}));m.position.copy(pos).add(new THREE.Vector3(0,1,0));scene.add(m);particles.push({mesh:m,life:.45,vel:new THREE.Vector3((Math.random()-.5)*5,Math.random()*4,(Math.random()-.5)*5)});}}
function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.vel.y-=9*dt;p.mesh.position.addScaledVector(p.vel,dt);if(p.life<=0){scene.remove(p.mesh);particles.splice(i,1);}}}
function screenToArena(x,y){const rect=canvas.getBoundingClientRect();const ndc=new THREE.Vector2((x/rect.width)*2-1,-(y/rect.height)*2+1);const ray=new THREE.Raycaster();ray.setFromCamera(ndc,camera);const t=-ray.ray.origin.y/ray.ray.direction.y;return ray.ray.origin.clone().addScaledVector(ray.ray.direction,t);} 
function updateCamera(){const offset=new THREE.Vector3(0,19,22);camera.position.copy(player.pos).add(offset);if(world.shake>0)camera.position.add(new THREE.Vector3((Math.random()-.5)*world.shake*3,0,(Math.random()-.5)*world.shake*3));camera.lookAt(player.pos.x,0,player.pos.z);world.shake=Math.max(0,world.shake-.02);} 
function updateStats(){document.getElementById('stats').innerHTML=`HP ${Math.ceil(player.hp)} / ${player.maxHp}<br>Damage ${player.damage}<br>Range ${player.punchRange.toFixed(1)}<br>Armor ${player.armor}<br>Combo ${world.combo}<br>Score ${world.score}<br>Goblins ${enemies.length}`;} 
function loop(){const dt=Math.min(clock.getDelta(),.033);if(world.phase==='combat'){updatePlayer(dt);updateEnemies(dt);}updateParticles(dt);updateCamera();updateStats();renderer.render(scene,camera);requestAnimationFrame(loop);} 
function resize(){const w=Math.floor(innerWidth*.78),h=Math.floor(innerHeight*.78);renderer.setSize(w,h,false);canvas.style.width='100vw';canvas.style.height='100vh';camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}
addEventListener('resize',resize);addEventListener('keydown',e=>{input.keys.add(e.code);if(e.code==='Space')player.dash=.18;if(e.code==='KeyF')startRun();});addEventListener('keyup',e=>input.keys.delete(e.code));addEventListener('mousemove',e=>input.mouse.set(e.clientX,e.clientY));addEventListener('mousedown',e=>{if(e.button===0)input.punch=true;});addEventListener('mouseup',e=>{if(e.button===0)input.punch=false;});
addLights();makeColosseum();player.mesh=makeCharacter(mats.player,1);scene.add(player.mesh);resize();showMenu();loop();